attack:
  name: cw
  norm: linf
  targeted: false
  epsilon:
  epsilon_scale:
  kappa: 0.0
  max_iterations: 1000
  learning_rate: 0.01
  binary_search_steps: 1
  initial_const: 1.0
  abort_early: true
  clip_min: 0.0
  clip_max: 1.0
  input_scale: zero_one

model:
  name: inception_v3
  backend: tensorflow
  input_scale: zero_one
  preprocessing: inception_v3

dataset:
  name: imagenet
  split: test
  start_index:
  n_samples: 100
  selection_strategy: random
  classes: all

success_criteria:
  skip_wrong_clean_prediction: true
  success_rule: adv_pred != clean_pred
