name: advsimage-ids
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - caffe
  - numpy=1.16.6
  - scipy=1.2.1
  - scikit-image=0.16.2
  - pandas=1.0.5
  - matplotlib=3.1.3
  - pillow=6.2.2
  - h5py=2.10.0
  - pytest=6.2.5
  - pyyaml=5.4.1
  - pip:
      - -r requirements.txt
